# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-15 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True, verbose_name='Имя')),
                ('description', models.TextField(verbose_name='Описание')),
                ('privileges', models.CharField(max_length=20, verbose_name='Привилегии')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='Логин')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('surname', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('age', models.PositiveIntegerField(default=18, verbose_name='Возраст')),
                ('email', models.CharField(max_length=30, verbose_name='e-mail')),
                ('phone', models.CharField(max_length=11, verbose_name='м.телефон')),
                ('password', models.CharField(max_length=30, verbose_name='Пароль')),
                ('id_category', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Privilege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True, verbose_name='Имя')),
            ],
        ),
    ]
