# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 00:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_auto_20170724_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 7, 24, 3, 8, 37, 491222), verbose_name='Дата'),
        ),
    ]
