# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-10 10:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_auto_20170724_0314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='id_request',
        ),
        migrations.RemoveField(
            model_name='order',
            name='id_user',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
