# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-10 11:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrdersApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PhotosessionInOrder',
            new_name='RequestInOrder',
        ),
        migrations.AlterModelOptions(
            name='requestinorder',
            options={'verbose_name': 'Request', 'verbose_name_plural': 'Requests'},
        ),
    ]
