# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-10 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0003_order_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, default=2000.0, max_digits=8),
        ),
    ]
